import { FileText, GitBranch, CheckCircle, ChartBar, ArrowRight } from '@phosphor-icons/react';
import './automation-preview.css';
export default function AutomationPreview({lang,paused,compact=false}:{lang:'es'|'en';paused:boolean;compact?:boolean}){
 const es=lang==='es';
 return <div className={`flow-preview ${compact?'flow-compact':''}`} data-paused={paused} role="img" aria-label={es?'Concepto visual de automatización: documentos, validación, revisión de excepciones y reporte.':'Automation concept: documents, validation, exception review and reporting.'}>
 <div className="flow-top"><span><i/> {es?'FLUJO OPERATIVO':'OPERATIONS FLOW'}</span><span>{es?'Concepto':'Concept'}</span></div>
 <div className="flow-scene" aria-hidden="true"><div className="flow-grid"/><div className="flow-doc doc-one"><FileText size={22}/><span>{es?'Producción':'Production'}<small>turno_01.xlsx</small></span></div><div className="flow-doc doc-two"><FileText size={22}/><span>{es?'Calidad':'Quality'}<small>incidencias.csv</small></span></div><svg className="flow-paths" viewBox="0 0 500 470" preserveAspectRatio="none"><path d="M90 85 V125 Q90 145 120 145 H220 Q250 145 250 170 V180"/><path d="M410 85 V125 Q410 145 380 145 H280 Q250 145 250 170 V180"/><path className="flow-pulse" d="M90 85 V125 Q90 145 120 145 H220 Q250 145 250 170 V180"/><path d="M250 280 V300 H385 V320 M250 300 H90 V365"/></svg><div className="flow-core"><GitBranch size={34}/><span>{es?'Validar y conectar':'Validate & connect'}</span><small>{es?'Reglas · trazabilidad':'Rules · traceability'}</small><div className="core-ring"/></div><div className="flow-exception"><span className="exception-dot"/>{es?'Excepción → revisión':'Exception → review'}</div><div className="flow-report"><div><ChartBar size={23}/><span>{es?'Reporte de turno':'Shift report'}</span><CheckCircle size={18}/></div><div className="flow-chart">{[35,62,47,84,68,94,76].map((n,i)=><i key={i} style={{height:`${n}%`,animationDelay:`${i*.12}s`}}/>)}</div><small>{es?'Consolidado · listo para revisar':'Consolidated · ready for review'}</small></div></div>
 <div className="flow-bottom"><span>{es?'Del trabajo repetitivo a un proceso claro.':'From repetitive work to a clear process.'}</span><ArrowRight size={19}/></div><p className="flow-disclaimer">{es?'Diseño de automatización · vista conceptual':'Automation design · concept preview'}</p></div>;
}
