import type { Lang } from './content';
export function professional(lang:Lang){
 const es=lang==='es';
 return {
  title:es?'Desarrollo web,':'Web development,',accent:es?'datos y automatización.':'data & automation.',
  intro:es?'Estudiante de Ingeniería en Software en la UANL. Hago aplicaciones que puedes probar aquí mismo.':'Software Engineering student at UANL. I build apps you can try right here.',
  projectsTitle:es?'Proyectos.':'Projects.',projectsIntro:es?'Todos funcionan: entra a cualquiera y pruébalo.':'All of them work: open any one and try it.',
  role:es?'Estudiante de Ingeniería en Software · UANL':'Software Engineering student · UANL',
  aboutTitle:es?'Perfil profesional.':'Professional profile.',
  about:es?'Estudio Ingeniería en Software en la UANL (2023–2028). He dado soporte de sistemas, validado datos y dado tutorías de programación. Hago interfaces web conectadas a bases de datos y APIs.':'I study Software Engineering at UANL (2023–2028). I have done systems support, data validation and programming tutoring. I build web interfaces connected to databases and APIs.',
  about2:es?'Primero entiendo el problema; luego compruebo que la solución funciona.':'First I understand the problem; then I verify the solution works.',
  profilePoints:es?[['Formación','Ingeniería en Software · UANL'],['Áreas','Web, datos y automatización'],['Experiencia','Soporte, validación y tutoría'],['Ubicación','Monterrey, Nuevo León']]:[['Education','Software Engineering · UANL'],['Focus','Web, data & automation'],['Experience','Support, validation & tutoring'],['Location','Monterrey, Nuevo León']],
  techTitle:es?'Herramientas.':'Tools.',
  skills:es?[
   {name:'Aplicaciones web',desc:'Interfaces responsivas y conectadas.',tools:['React','TypeScript','JavaScript','HTML','CSS','Vite']},
   {name:'Datos y análisis',desc:'Limpieza, consultas y reportes.',tools:['Python','Pandas','SQL','R','Excel']},
   {name:'Integraciones',desc:'Nube, autenticación y servicios.',tools:['Supabase','REST APIs','Node.js']},
   {name:'Automatización',desc:'Scripts para tareas repetitivas.',tools:['Scripts programados','Procesamiento de archivos']},
   {name:'Móvil',desc:'Apps web empaquetadas para Android.',tools:['Capacitor','Android']}
  ]:[
   {name:'Web applications',desc:'Responsive, connected interfaces.',tools:['React','TypeScript','JavaScript','HTML','CSS','Vite']},
   {name:'Data & analysis',desc:'Cleaning, queries and reports.',tools:['Python','Pandas','SQL','R','Excel']},
   {name:'Integrations',desc:'Cloud, authentication and services.',tools:['Supabase','REST APIs','Node.js']},
   {name:'Automation',desc:'Scripts for repetitive tasks.',tools:['Scheduled scripts','File processing']},
   {name:'Mobile',desc:'Web apps packaged for Android.',tools:['Capacitor','Android']}
  ],
  projects:[
   {id:'club',slug:'club-nfc',title:es?'NFC para negocios':'NFC for businesses',kind:es?'Atención a clientes':'Customer care',status:es?'Funcional':'Working',desc:es?'Atención a clientes rápida con un tap: el celular toca un chip, se suma un sello en el Wallet y WhatsApp hace el resto.':'Fast customer care with one tap: the phone touches a chip, a stamp lands in the Wallet and WhatsApp does the rest.',tags:['React','TypeScript','NFC','Wallet','WhatsApp API'],metrics:[['1',es?'tap por visita, sin app':'tap per visit, no app'],['3',es?'mensajes automáticos':'automatic messages'],['1',es?'sello al día: sin trampas':'stamp a day: no cheating']] as [string,string][],media:'club',how:es?[['Tap','El cliente acerca su celular al chip de la cuenta. La primera vez deja nombre, WhatsApp y cumpleaños.'],['Wallet','Su tarjeta de sellos vive en Apple o Google Wallet y se actualiza sola en cada visita.'],['WhatsApp','A las 2 h pide una reseña; si deja de venir, lo invita a volver; antes de su cumpleaños, le manda una promo.']]:[['Tap','The customer brings their phone to the bill’s chip. The first time they leave name, WhatsApp and birthday.'],['Wallet','Their stamp card lives in Apple or Google Wallet and updates itself on every visit.'],['WhatsApp','After 2 h it asks for a review; if they stop coming, it invites them back; before their birthday, it sends a promo.']],link:'',action:es?'Probarlo':'Try it'},
   {id:'csv',slug:'analizador-csv',title:es?'Analizador de CSV':'CSV Analyzer',kind:es?'Datos':'Data',status:es?'Funcional':'Working',desc:es?'Encuentra duplicados, valores mal escritos, fechas mezcladas y reglas rotas. Corrige lo mecánico con un clic.':'Finds duplicates, misspelled values, mixed dates and broken rules. Fixes the mechanical ones in one click.',tags:['TypeScript','React','Calidad de datos','CSV'],metrics:[['7',es?'tipos de problema':'issue types'],['1',es?'clic para limpiar lo mecánico':'click to clean the mechanical ones'],['0',es?'servidores: tu archivo no sale':'servers: your file stays']] as [string,string][],media:'analizador',how:es?[['Lee','Abre tu CSV en el navegador y detecta el tipo de cada columna.'],['Revisa','Siete reglas buscan duplicados, mayúsculas y acentos distintos, fechas mezcladas, negativos y reglas de negocio.'],['Limpia','Corrige lo mecánico con un clic, marca lo que requiere criterio y te da el CSV limpio.']]:[['Read','Opens your CSV in the browser and detects each column’s type.'],['Review','Seven rules look for duplicates, case and accent variants, mixed dates, negatives and business rules.'],['Clean','Fixes the mechanical issues in one click, flags what needs judgment and gives you the clean CSV.']],link:'',action:es?'Probarlo':'Try it'},
   {id:'turno',slug:'entrega-de-turno',title:es?'Entrega de turno':'Shift handover',kind:es?'Automatización · calidad':'Automation · quality',status:es?'Funcional':'Working',desc:es?'Las incidencias de calidad pasan de un turno a otro con responsable, evidencia y cierre. Nada se queda en un chat.':'Quality incidents move from one shift to the next with an owner, evidence and a closure. Nothing gets lost in a chat.',tags:['React','TypeScript','Automatización','Calidad'],metrics:[['3',es?'estados: abierta, en curso, cerrada':'states: open, in progress, closed'],['0',es?'cierres sin evidencia':'closures without evidence'],['1',es?'clic para entregar el turno':'click to hand over the shift']] as [string,string][],media:'turno',how:es?[['Registra','Cada incidencia queda ligada a su línea y su lote, con severidad.'],['Asigna','Tiene responsable y siguiente acción; sólo se cierra con evidencia.'],['Entrega','Al final del turno sale el resumen de lo abierto para el siguiente equipo.']]:[['Log','Each incident is tied to its line and batch, with a severity.'],['Assign','It has an owner and next action; it can only be closed with evidence.'],['Hand over','At the end of the shift, a summary of open work goes to the next team.']],link:'',action:es?'Probarlo':'Try it'},
   {id:'vibe',slug:'vibemap',title:'VibeMap',kind:es?'Hackathon · equipo de 3':'Hackathon · team of 3',status:es?'Publicado':'Published',desc:es?'Sueltas la carpeta de un proyecto y lo ves como mapa mental: dónde arranca, qué archivo usa a cuál y qué está sobrando.':'Drop a project folder and see it as a mind map: where it starts, which file uses which, and what is left over.',tags:['React','TypeScript','Análisis de código','Godot'],metrics:[['4',es?'lenguajes: TS, JS, Python y GDScript':'languages: TS, JS, Python and GDScript'],['0',es?'servidores: tu código no sale':'servers: your code stays']] as [string,string][],media:'vibemap',how:es?[['Lee','Recorre la carpeta y encuentra imports, funciones y clases de cada archivo.'],['Conecta','Une quién usa a quién y quién llama a cada función, también entre archivos.'],['Explica','Te da el mapa, el recorrido desde la entrada y las alertas: ciclos, archivos sueltos y funciones sin uso.']]:[['Read','Walks the folder and finds each file’s imports, functions and classes.'],['Connect','Links who uses whom and who calls each function, across files too.'],['Explain','Gives you the map, the path from the entry point and alerts: cycles, loose files and unused functions.']],link:'https://vibemap-brunich.vercel.app',action:es?'Abrir VibeMap':'Open VibeMap'},
   {id:'punto',slug:'punto-u',title:'Punto U',kind:es?'App web y Android':'Web & Android app',status:es?'Publicada':'Published',desc:es?'Estudiantes de la UANL publican favores en un mapa del campus y los cambian por dinero, tiempo o estudio.':'UANL students post favors on a campus map and trade them for money, time or study help.',tags:['React','Supabase','Capacitor'],metrics:[] as [string,string][],media:'punto-u',how:es?[['Perfil','Entras con tu matrícula y tu facultad.'],['Misión','Publicas un favor en el mapa del campus: dinero, tiempo o estudio.'],['Trato','Otro estudiante la acepta, la cumplen y ambos ganan puntos.']]:[['Profile','Sign in with your student ID and faculty.'],['Mission','Post a favor on the campus map: money, time or study help.'],['Deal','Another student accepts it, you complete it and both earn points.']],link:'https://punto-u-app.vercel.app',action:es?'Abrir aplicación':'Open application'}
  ]
 };
}
