import type { Lang } from './content';
export function professional(lang:Lang){
 const es=lang==='es';
 return {
  title:es?'Desarrollo web,':'Web development,',accent:es?'datos y automatización.':'data & automation.',
  intro:es?'Estudiante de Ingeniería en Software en la UANL. Hago aplicaciones que puedes probar aquí mismo.':'Software Engineering student at UANL. I build apps you can try right here.',
  projectsTitle:es?'Proyectos.':'Projects.',projectsIntro:es?'Herramientas para negocios y manufactura. Todas funcionan: entra a cualquiera y pruébala.':'Tools for businesses and manufacturing. All of them work: open any one and try it.',
  role:es?'Estudiante de Ingeniería en Software · UANL':'Software Engineering student · UANL',
  aboutTitle:es?'Perfil profesional.':'Professional profile.',
  about:es?'Estudio Ingeniería en Software en la UANL (2023–2028). He dado soporte de sistemas, validado datos y dado tutorías de programación. Hago interfaces web conectadas a bases de datos y APIs.':'I study Software Engineering at UANL (2023–2028). I have done systems support, data validation and programming tutoring. I build web interfaces connected to databases and APIs.',
  about2:es?'Primero entiendo el problema; luego compruebo que la solución funciona.':'First I understand the problem; then I verify the solution works.',
  profilePoints:es?[['Formación','Ingeniería en Software · UANL'],['Áreas','Web, datos y automatización'],['Experiencia','Soporte, validación y tutoría'],['Ubicación','Monterrey, Nuevo León']]:[['Education','Software Engineering · UANL'],['Focus','Web, data & automation'],['Experience','Support, validation & tutoring'],['Location','Monterrey, Nuevo León']],
  techTitle:es?'Herramientas.':'Tools.',
  skills:es?[
   {name:'Aplicaciones web',desc:'Interfaces responsivas y conectadas.',tools:['React','TypeScript','JavaScript','HTML','CSS','Vite']},
   {name:'Datos y análisis',desc:'Limpieza, consultas y reportes.',tools:['Python','Pandas','SQL','R','Excel']},
   {name:'Integraciones',desc:'Nube, autenticación y servicios.',tools:['Supabase','REST APIs','Node.js']},
   {name:'Automatización',desc:'Scripts para tareas repetitivas.',tools:['Scripts programados','Procesamiento de archivos']},
   {name:'Móvil',desc:'Apps web empaquetadas para Android.',tools:['Capacitor','Android']}
  ]:[
   {name:'Web applications',desc:'Responsive, connected interfaces.',tools:['React','TypeScript','JavaScript','HTML','CSS','Vite']},
   {name:'Data & analysis',desc:'Cleaning, queries and reports.',tools:['Python','Pandas','SQL','R','Excel']},
   {name:'Integrations',desc:'Cloud, authentication and services.',tools:['Supabase','REST APIs','Node.js']},
   {name:'Automation',desc:'Scripts for repetitive tasks.',tools:['Scheduled scripts','File processing']},
   {name:'Mobile',desc:'Web apps packaged for Android.',tools:['Capacitor','Android']}
  ],
  projects:[
   {id:'club',pitch:es?'Que vuelvan, sin quitarles tiempo.':'Bring them back, without taking their time.',slug:'club-nfc',title:es?'NFC para negocios':'NFC for businesses',kind:es?'Atención a clientes':'Customer care',status:es?'Funcional':'Working',desc:es?'Una tarjeta de sellos en el celular, como la de cartón de cualquier café: cada visita suma uno y al completarla hay premio. Es para que el cliente vuelva y el negocio lo atienda mejor, y al cliente le cuesta un segundo: acercar el celular al chip.':'A stamp card on the phone, like any coffee shop’s paper one: every visit adds a stamp and a full card earns a reward. It gives customers a reason to come back and the business a way to look after them, and it costs the customer one second: tapping the chip.',tags:['React','TypeScript','NFC','Web NFC','QR','WhatsApp'],metrics:[['1',es?'segundo por visita, sin app':'second per visit, no app'],['0',es?'apps que instalar':'apps to install'],['1',es?'sello al día: sin trampas':'stamp a day: no cheating']] as [string,string][],media:'club',how:es?[['Tap','El cliente acerca su celular al chip de la cuenta o del mostrador. Se abre su tarjeta: sin app y sin llenar nada.'],['Sello','Suma uno por visita, máximo uno al día. Con la tarjeta llena, el premio que el negocio eligió: un postre, un café, un descuento.'],['Vuelve','Los sellos le dan una razón para regresar, y al negocio una forma de atenderlo: pedir su reseña o invitarlo de nuevo.'],['Menú','El mismo chip o un QR en la mesa abre la carta; el cliente arma su pedido y lo manda por WhatsApp.']]:[['Tap','The customer taps their phone on the chip at the bill or the counter. Their card opens: no app, nothing to fill in.'],['Stamp','One per visit, at most one a day. A full card earns the reward the business chose: a dessert, a coffee, a discount.'],['Return','Stamps give them a reason to come back, and the business a way to look after them: asking for a review or inviting them again.'],['Menu','The same chip or a QR on the table opens the menu; the customer builds an order and sends it via WhatsApp.']],link:'',action:es?'Probarlo':'Try it'},
   {id:'csv',pitch:es?'Tu reporte, limpio en un clic.':'Your report, clean in one click.',slug:'analizador-csv',title:es?'Analizador de CSV':'CSV Analyzer',kind:es?'Datos':'Data',status:es?'Funcional':'Working',desc:es?'Encuentra duplicados, valores mal escritos, fechas mezcladas y reglas rotas, y corrige lo mecánico con un clic. Después lo grafica sin abrir Excel y le puedes preguntar en SQL.':'Finds duplicates, misspelled values, mixed dates and broken rules, and fixes the mechanical ones in one click. Then it charts it without Excel, and you can query it in SQL.',tags:['TypeScript','React','SQL (SQLite)','Gráficas SVG','CSV'],metrics:[['7',es?'tipos de problema':'issue types'],['8',es?'tipos de gráfica':'chart types'],['0',es?'servidores: tu archivo no sale':'servers: your file stays']] as [string,string][],media:'analizador',how:es?[['Lee','Abre tu CSV en el navegador y detecta el tipo de cada columna.'],['Revisa','Siete reglas buscan duplicados, mayúsculas y acentos distintos, fechas mezcladas, negativos y reglas de negocio.'],['Limpia','Corrige lo mecánico con un clic y marca lo que requiere criterio.'],['Grafica','Sugiere la gráfica que tiene sentido para tus columnas; la bajas en PNG o SVG, o copias los datos a Canva, Flourish o Datawrapper.'],['Pregunta','El archivo se vuelve una tabla de SQLite dentro del navegador: escribe tu consulta o usa un ejemplo, y grafica el resultado.']]:[['Read','Opens your CSV in the browser and detects each column’s type.'],['Review','Seven rules look for duplicates, case and accent variants, mixed dates, negatives and business rules.'],['Clean','Fixes the mechanical issues in one click and flags what needs judgment.'],['Chart','Suggests the chart that fits your columns; download it as PNG or SVG, or copy the data to Canva, Flourish or Datawrapper.'],['Ask','The file becomes a SQLite table inside the browser: write your query or use an example, and chart the result.']],link:'',action:es?'Probarlo':'Try it'},
   {id:'turno',pitch:es?'Nada se pierde entre turnos.':'Nothing gets lost between shifts.',slug:'entrega-de-turno',title:es?'Entrega de turno':'Shift handover',kind:es?'Automatización · calidad':'Automation · quality',status:es?'Funcional':'Working',desc:es?'Las incidencias de calidad pasan de un turno a otro con responsable, evidencia y cierre. Nada se queda en un chat.':'Quality incidents move from one shift to the next with an owner, evidence and a closure. Nothing gets lost in a chat.',tags:['React','TypeScript','Automatización','Calidad'],metrics:[['3',es?'estados: abierta, en curso, cerrada':'states: open, in progress, closed'],['0',es?'cierres sin evidencia':'closures without evidence'],['1',es?'clic para entregar el turno':'click to hand over the shift']] as [string,string][],media:'turno',how:es?[['Registra','Cada incidencia queda ligada a su línea y su lote, con severidad.'],['Asigna','Pasa a «en curso» con responsable y siguiente acción; sólo se cierra con foto de evidencia.'],['Entrega','Al final sale el resumen de lo pendiente, ordenado por severidad, listo para copiar o mandar por WhatsApp.']]:[['Log','Each incident is tied to its line and batch, with a severity.'],['Assign','It moves to “in progress” with an owner and next action; it only closes with a photo as evidence.'],['Hand over','At the end, a summary of open work sorted by severity, ready to copy or send via WhatsApp.']],link:'',action:es?'Probarlo':'Try it'},
   {id:'agente',slug:'asistente-ia-local',pitch:es?'Atiende clientes y consulta tu base, sin pagar por mensaje.':'Serves customers and queries your data, with no per-message fees.',title:es?'Asistente de IA local':'Local AI assistant',kind:es?'IA · atención y datos':'AI · service and data',status:es?'En desarrollo · aprendiendo':'In development · learning',desc:es?'Un asistente que corre en el equipo del negocio con un modelo abierto: contesta precios, existencias y pedidos, consulta la base interna sólo para leer y pasa a una persona lo que no sabe. Sin API por mensaje y sin que los datos salgan. Lo estoy desarrollando; aquí ves lo que hará.':'An assistant that runs on the business’s own machine with an open model: it answers prices, stock and orders, queries the internal database read-only and hands what it cannot answer to a person. No per-message API and data never leaves. I am building it; this shows what it will do.',tags:['IA local','Ollama','Qwen3','SQL de sólo lectura','Docker'],metrics:[['0',es?'pagos por mensaje':'per-message fees'],['1',es?'archivo para configurarlo':'config file'],['4',es?'formas de instalarlo':'ways to install it']] as [string,string][],media:'agente',how:es?[['Instala','En una PC del negocio o en un servidor rentado: modelo abierto con Ollama, el agente y un panel, con un solo comando.'],['Configura','En un archivo: qué catálogo y qué tablas lee, cómo habla y a quién le pasa lo que no sabe. Sólo lectura, siempre.'],['Atiende','Contesta citando de dónde sacó cada dato; lo que no está en sus fuentes no lo inventa: lo escala.']]:[['Install','On a business PC or a rented server: open model on Ollama, the agent and a dashboard, with one command.'],['Configure','In one file: which catalog and tables it reads, how it talks and who gets what it cannot answer. Read-only, always.'],['Serve','It cites where each fact came from; anything outside its sources is escalated, not invented.']],link:'',action:es?'Ver la demo':'See the demo'},
   {id:'planta',slug:'planta',pitch:es?'Tres reportes, un OEE, cero copiar y pegar.':'Three reports, one OEE, zero copy-paste.',title:es?'Planta: consolidador y OEE':'Plant: consolidator & OEE',kind:es?'Automatización · manufactura':'Automation · manufacturing',status:es?'Funcional':'Working',desc:es?'Subes el Excel de producción, el de calidad y el de paros del turno. Se cruzan solos, se marcan las incoherencias, el OEE de cada línea y el reporte listo en Excel.':'Upload the shift’s production, quality and downtime spreadsheets. They cross-check themselves, flag what does not add up, compute each line’s OEE and output an Excel report.',tags:['React','TypeScript','Excel (SheetJS)','OEE','Automatización'],metrics:[['3',es?'reportes cruzados solos':'reports cross-checked'],['6',es?'reglas de excepción':'exception rules'],['4',es?'hojas en el reporte':'sheets in the report']] as [string,string][],media:'planta',how:es?[['Sube','Producción, calidad y paros en Excel o CSV. Reconoce las columnas por nombre, aunque vengan con acentos o en otro orden.'],['Cruza','Une cada lote por fecha, turno y línea, y marca las incoherencias: lotes sin inspección, inspecciones de lotes que no existen, rechazo alto, plan incumplido.'],['Mide','OEE por línea (disponibilidad × rendimiento × calidad), dónde se pierde el tiempo y el Pareto de paros. Sale en Excel o por WhatsApp.']]:[['Upload','Production, quality and downtime in Excel or CSV. Columns are recognized by name, even with accents or in another order.'],['Cross-check','Joins each batch by date, shift and line, and flags mismatches: uninspected batches, inspections of unknown batches, high rejection, missed plan.'],['Measure','OEE per line (availability × performance × quality), where time is lost and a downtime Pareto. Out to Excel or WhatsApp.']],link:'',action:es?'Probarlo':'Try it'},
   {id:'spc',slug:'graficas-de-control',pitch:es?'Saber si la máquina se está desajustando antes de que salga pieza mala.':'Know the machine is drifting before a bad part comes out.',title:es?'Gráficas de control (SPC)':'Control charts (SPC)',kind:es?'Calidad · manufactura':'Quality · manufacturing',status:es?'Funcional':'Working',desc:es?'Subes las mediciones de una pieza y dice si el proceso está bajo control, qué puntos avisan que algo cambió y si alcanza la tolerancia (Cp y Cpk). En palabras, con qué revisar primero.':'Upload a part’s measurements and it tells you whether the process is in control, which points signal a change and whether it can hold the tolerance (Cp and Cpk). In plain words, with what to check first.',tags:['React','TypeScript','SPC','Estadística','Gráficas SVG'],metrics:[['5',es?'reglas de Western Electric':'Western Electric rules'],['2',es?'gráficas: X̄-R o I-MR':'charts: X̄-R or I-MR'],['0',es?'servidores: tus datos no salen':'servers: your data stays']] as [string,string][],media:'spc',how:es?[['Sube','Un CSV o Excel con las mediciones. Si trae una columna de muestra o subgrupo, arma la gráfica X̄-R; si no, la de individuales.'],['Vigila','Calcula los límites con un periodo estable y marca los puntos que rompen alguna de las cinco reglas: fuera de límite, tendencia, corrimiento…'],['Decide','Te dice qué suele significar cada señal y si el proceso cabe en la tolerancia, con Cp, Cpk y las piezas que ya salieron.']]:[['Upload','A CSV or Excel with the measurements. With a sample or subgroup column it builds an X̄-R chart; otherwise, individuals.'],['Watch','Computes the limits from a stable period and flags points that break any of the five rules: beyond limits, trend, shift…'],['Decide','Tells you what each signal usually means and whether the process fits the tolerance, with Cp, Cpk and the parts already out.']],link:'',action:es?'Probarlo':'Try it'},
   {id:'inventario',slug:'inventario',pitch:es?'La cámara del celular como lector de códigos.':'Your phone camera as a barcode scanner.',title:es?'Inventario con la cámara':'Camera inventory',kind:es?'Negocios · móvil':'Business · mobile',status:es?'Funcional':'Working',desc:es?'Escaneas el código de barras con el celular y suma una entrada, resta una venta o cuenta el anaquel. Avisa lo que está bajo el mínimo y arma la lista para el proveedor.':'Scan a barcode with your phone and it adds stock, records a sale or counts the shelf. It flags what is below minimum and builds the list for the supplier.',tags:['React','TypeScript','Cámara (ZXing)','EAN-13','WhatsApp'],metrics:[['3',es?'modos: entrada, venta y conteo':'modes: in, sale and count'],['0',es?'lectores que comprar':'scanners to buy'],['1',es?'lista de compras automática':'automatic shopping list']] as [string,string][],media:'inventario',how:es?[['Escanea','Con la cámara, con una foto del código o escribiéndolo. Si el código no existe, lo das de alta ahí mismo.'],['Cuenta','En modo conteo escaneas cada pieza; al cerrar, el sistema toma lo contado y registra la diferencia.'],['Resurte','Lo que está bajo el mínimo sale en una lista para mandar por WhatsApp. Y si tus productos no traen código, imprime etiquetas EAN-13.']]:[['Scan','With the camera, a photo of the code or typing it. Unknown codes are registered on the spot.'],['Count','In count mode you scan every unit; closing it takes the counted stock and logs the difference.'],['Restock','Items below minimum become a list to send via WhatsApp. And if products have no code, print EAN-13 labels.']],link:'',action:es?'Probarlo':'Try it'},
   {id:'vibe',pitch:es?'Cualquier código, de un vistazo.':'Any codebase, at a glance.',slug:'vibemap',title:'VibeMap',kind:es?'Hackathon · equipo de 3':'Hackathon · team of 3',status:es?'Publicado':'Published',desc:es?'Sueltas la carpeta de un proyecto y lo ves como mapa mental: dónde arranca, qué archivo usa a cuál y qué está sobrando.':'Drop a project folder and see it as a mind map: where it starts, which file uses which, and what is left over.',tags:['React','TypeScript','Análisis de código','Godot'],metrics:[['4',es?'lenguajes: TS, JS, Python y GDScript':'languages: TS, JS, Python and GDScript'],['0',es?'servidores: tu código no sale':'servers: your code stays']] as [string,string][],media:'vibemap',how:es?[['Lee','Recorre la carpeta y encuentra imports, funciones y clases de cada archivo.'],['Conecta','Une quién usa a quién y quién llama a cada función, también entre archivos.'],['Explica','Te da el mapa, el recorrido desde la entrada y las alertas: ciclos, archivos sueltos y funciones sin uso.']]:[['Read','Walks the folder and finds each file’s imports, functions and classes.'],['Connect','Links who uses whom and who calls each function, across files too.'],['Explain','Gives you the map, the path from the entry point and alerts: cycles, loose files and unused functions.']],link:'https://vibemap-brunich.vercel.app',action:es?'Abrir VibeMap':'Open VibeMap'},
   {id:'punto',pitch:es?'El campus, cambiando favores.':'The campus, trading favors.',slug:'punto-u',title:'Punto U',kind:es?'App web y Android':'Web & Android app',status:es?'Publicada':'Published',desc:es?'Estudiantes de la UANL publican favores en un mapa del campus y los cambian por dinero, tiempo o estudio.':'UANL students post favors on a campus map and trade them for money, time or study help.',tags:['React','Supabase','Capacitor'],metrics:[] as [string,string][],media:'punto-u',how:es?[['Perfil','Entras con tu matrícula y tu facultad.'],['Misión','Publicas un favor en el mapa del campus: dinero, tiempo o estudio.'],['Trato','Otro estudiante la acepta, la cumplen y ambos ganan puntos.']]:[['Profile','Sign in with your student ID and faculty.'],['Mission','Post a favor on the campus map: money, time or study help.'],['Deal','Another student accepts it, you complete it and both earn points.']],link:'https://punto-u-app.vercel.app',action:es?'Abrir aplicación':'Open application'}
  ]
 };
}
