import type { Lang } from './content';
export function professional(lang:Lang){
 const es=lang==='es';
 return {
  title:es?'Desarrollo web,':'Web development,',accent:es?'datos y automatización.':'data & automation.',
  intro:es?'Soy Bruno Salas, estudiante de Ingeniería en Software. Desarrollo aplicaciones web y soluciones para analizar datos y automatizar rutinas concretas.':'I’m Bruno Salas, a Software Engineering student. I develop web applications and solutions for analyzing data and automating specific workflows.',
  secondary:es?'También trabajo con escenas 3D, animación y shaders para game development.':'I also work with 3D scenes, animation and shaders for game development.',
  projectsTitle:es?'Proyectos y aplicaciones.':'Projects & applications.',projectsIntro:es?'Qué resuelven, cómo están construidos y qué puedes probar.':'What they solve, how they’re built, and what you can try.',
  role:es?'Estudiante de Ingeniería en Software · UANL':'Software Engineering student · UANL',
  dataTitle:es?'Prueba el analizador de datos.':'Try the data inspector.',dataIntro:es?'Carga un CSV, revisa su calidad y descarga una versión limpia. El archivo se procesa en tu navegador.':'Upload a CSV, inspect its quality and download a cleaned version. Your file is processed in your browser.',
  automationTitle:es?'Del contexto a la acción.':'From context to action.',automationIntro:es?'Selecciona un recorrido para conocer el problema, la información relevante y la siguiente decisión.':'Select a workflow to explore the problem, relevant information and next decision.',
  aboutTitle:es?'Perfil profesional.':'Professional profile.',
  about:es?'Estudiante de Ingeniería en Software en la UANL (2023–2028), con experiencia en soporte de sistemas, validación de datos y tutoría de programación. Desarrollo interfaces web e integro bases de datos y APIs.':'Software Engineering student at UANL (2023–2028), with experience in system support, data validation and programming tutoring. I develop web interfaces and integrate databases and APIs.',
  about2:es?'Mi enfoque es entender el problema, separar responsabilidades, comprobar resultados y documentar lo necesario para mantener el proyecto.':'My approach is to understand the problem, separate responsibilities, verify results and document what is needed to maintain the project.',
  profilePoints:es?[['Formación','Ingeniería en Software · UANL'],['Áreas','Web, datos y automatización'],['Experiencia','Soporte, validación y tutoría'],['Ubicación','Monterrey, Nuevo León']]:[['Education','Software Engineering · UANL'],['Focus','Web, data & automation'],['Experience','Support, validation & tutoring'],['Location','Monterrey, Nuevo León']],
  techTitle:es?'Capacidades y herramientas.':'Capabilities & tools.',
  skills:es?[
   {name:'Aplicaciones web',desc:'Interfaces responsivas y experiencias conectadas.',tools:['React','TypeScript','JavaScript','HTML','CSS','Vite']},
   {name:'Datos y análisis',desc:'Limpieza, consultas, cruces de información y reportes.',tools:['Python','Pandas','SQL','R','Excel']},
   {name:'Integraciones',desc:'Datos en la nube, autenticación y consumo de servicios.',tools:['Supabase','REST APIs','Node.js']},
   {name:'Automatización',desc:'Scripts para tareas repetitivas y procesamiento de archivos.',tools:['Scripts programados','Procesamiento de archivos']},
   {name:'Gráficos y móvil',desc:'Una especialidad adicional para productos interactivos.',tools:['Godot','GDScript','Shaders','Capacitor','Android']}
  ]:[
   {name:'Web applications',desc:'Responsive interfaces and connected experiences.',tools:['React','TypeScript','JavaScript','HTML','CSS','Vite']},
   {name:'Data & analysis',desc:'Cleaning, queries, data joins and reports.',tools:['Python','Pandas','SQL','R','Excel']},
   {name:'Integrations',desc:'Cloud data, authentication and service integrations.',tools:['Supabase','REST APIs','Node.js']},
   {name:'Automation',desc:'Scripts for repetitive tasks and file processing.',tools:['Scripts programados','Procesamiento de archivos']},
   {name:'Graphics & mobile',desc:'An additional specialty for interactive products.',tools:['Godot','GDScript','Shaders','Capacitor','Android']}
  ],
  graphicsTitle:es?'Escenas 3D y game development.':'3D scenes & game development.',
  graphicsIntro:es?'Trabajo adicional en IA Rogue: entornos, materiales y estilos de renderizado. Estas son capturas del proyecto real en desarrollo.':'Additional work on IA Rogue: environments, materials and rendering styles. These are captures of the actual project in development.',
  galleryLabels:es?['Bosque','Pixel grueso','Pixel fino','3D sin pixelado']:['Forest','Coarse pixels','Fine pixels','Unpixelated 3D'],
  sceneTitle:es?'Roca, luz y agua en movimiento.':'Rock, light and moving water.',
  sceneIntro:es?'Estudio interactivo para comparar materiales sobre la misma escena. Mueve la división o activa el recorrido automático.':'An interactive study comparing materials on the same scene. Drag the divider or enable automatic comparison.',
  projects:[
   {id:'punto',title:'Punto U',kind:es?'Aplicación web y móvil':'Web & mobile application',status:es?'Aplicación publicada':'Published application',desc:es?'Conecta estudiantes mediante perfiles y misiones de campus, con una base web preparada para Android.':'Connects students through profiles and campus missions, with a web foundation packaged for Android.',tags:['React','Supabase','Capacitor'],media:'punto-u',challenge:es?'Conectar una interfaz universitaria con datos persistentes y llevarla también a móvil.':'Connect a university interface to persistent data and bring it to mobile.',work:es?'React y Vite para la interfaz, integración con Supabase y empaquetado con Capacitor. Flujo de perfiles universitarios y datos en la nube.':'React and Vite interface, Supabase integration and Capacitor packaging. University profiles and cloud data.',result:es?'La aplicación web está publicada. Puedes explorar su pantalla de acceso; el APK Android fue generado para pruebas.':'The web app is published. You can explore its entry screen; an Android APK was generated for testing.',link:'https://punto-u-app.vercel.app',action:es?'Abrir aplicación':'Open application'},
   {id:'vibe',title:'VibeMap',kind:es?'Arquitectura de software · Hackathon':'Software architecture · Hackathon',status:es?'Proyecto de equipo':'Team project',desc:es?'Ayuda a entender un proyecto con diagramas, analogías y código comentado. Construido en equipo durante un hackathon.':'Helps explain a project through diagrams, analogies and commented code. Built as a team during a hackathon.',tags:['React','TypeScript','Gemini','Mermaid'],media:'vibemap',challenge:es?'Hacer comprensible la estructura del software para quien está aprendiendo a programar.':'Make software structure understandable for people learning to program.',work:es?'Proyecto de un equipo de tres personas. Integra una interfaz React/TypeScript, respuestas estructuradas de una API de IA y diagramas Mermaid.':'A three-person team project. Integrates a React/TypeScript interface, structured AI API responses and Mermaid diagrams.',result:es?'Repositorio público y captura de la aplicación original. No se presenta como una API de IA activa dentro de este portafolio.':'Public repository and capture of the original app. It is not presented as a live AI API inside this portfolio.',link:'https://github.com/CharlsMex24/VibeMap_Hackathon',action:es?'Ver repositorio':'View repository'},
   {id:'impact',title:es?'Mapa de impacto':'Change impact map',kind:es?'Ingeniería de software · Análisis de cambios':'Software engineering · Change analysis',status:es?'Dependencias · evidencia · contexto':'Dependencies · evidence · context',desc:es?'De una modificación a sus consecuencias: una vista del recorrido entre interfaz, servicios y datos, con explicaciones orientadas a quien empieza a trabajar en el repositorio.':'From a change to its consequences: a view of the path through interface, services and data, with explanations for developers new to the repository.',tags:['TypeScript','Análisis estático','Git'],media:'impact',challenge:es?'Entender qué revisar antes de modificar código ajeno, sin recorrer todo el repositorio ni depender de un resumen sin referencias.':'Understand what to inspect before changing unfamiliar code, without reading the entire repository or relying on an unreferenced summary.',work:es?'Diseño centrado en proyectos React y TypeScript: relaciones verificables entre archivos, recorrido por funcionalidad y explicaciones en español técnico claro. Cada conexión distinguirá evidencia directa de relaciones que requieren revisión.':'Design focused on React and TypeScript projects: verifiable file relationships, feature-oriented navigation and clear technical explanations. Connections distinguish direct evidence from relationships requiring review.',result:es?'Objetivo: concentrar la revisión en dependencias relevantes y pruebas relacionadas. La selección de un nodo muestra qué hace, por qué importa para el cambio y dónde comprobarlo.':'Goal: focus review on relevant dependencies and related tests. Selecting a node explains its purpose, relevance to the change and where to verify it.',link:'#automation',action:es?'Explorar el recorrido':'Explore the workflow'},
   {id:'quality',title:es?'Continuidad de calidad':'Quality handover',kind:es?'Manufactura · Seguimiento entre turnos':'Manufacturing · Cross-shift follow-up',status:es?'Responsables · evidencia · cierre':'Ownership · evidence · closure',desc:es?'Una vista de las acciones que siguen abiertas al cambiar de turno: defecto, lote afectado, responsable, evidencia y siguiente decisión, sin perder el contexto del registro original.':'A view of actions still open at shift change: defect, affected batch, owner, evidence and next decision, retaining the context of the original record.',tags:['Trazabilidad','Control de acceso','Auditoría'],media:'data',challenge:es?'Evitar que un problema registrado pierda seguimiento entre hojas de cálculo, mensajes y relevos de personal.':'Keep recorded issues from losing follow-up across spreadsheets, messages and staff handovers.',work:es?'Diseño de una capa de seguimiento sobre los registros existentes: referencias a lote y línea, acciones con vencimiento, evidencia vinculada y verificación de cierre por rol.':'A follow-up layer over existing records: batch and line references, action deadlines, linked evidence and role-based closure verification.',result:es?'Objetivo: entregar cada turno con pendientes claros y contexto suficiente para actuar. Los defectos recurrentes y las acciones vencidas quedan visibles sin volver a capturar toda la operación.':'Goal: hand over each shift with clear pending actions and sufficient context to act. Recurring defects and overdue actions remain visible without re-entering the entire operation.',link:'#automation',action:es?'Explorar el recorrido':'Explore the workflow'}
  ],
  automations:es?[
   {title:'Mapa de impacto de cambios',who:'Para desarrolladores junior que se incorporan a un proyecto React/TypeScript o retoman código que no escribieron.',steps:['Seleccionar un cambio o funcionalidad','Recorrer archivos y dependencias','Entender la relación con el cambio','Preparar una revisión con evidencia'],deliverable:'Un mapa navegable que vincula el cambio con archivos, responsabilidades y pruebas relacionadas.',stack:'TypeScript · AST · Git · Visualización de grafos',boundary:'Alcance inicial: relaciones estáticas verificables. Las llamadas dinámicas y las dependencias externas requieren revisión explícita.'},
   {title:'Continuidad de calidad entre turnos',who:'Para supervisores y equipos de calidad que reciben incidencias abiertas de otro turno y necesitan decidir qué atender.',steps:['Vincular incidencia, lote y línea','Definir responsable y siguiente acción','Revisar evidencia y autorizar cierre','Entregar pendientes al siguiente turno'],deliverable:'Una vista de entrega de turno con responsables, fechas, evidencia y referencias al registro de origen.',stack:'React · PostgreSQL · Permisos por rol',boundary:'Enfoque: seguimiento de acciones sobre registros existentes. El método de integración depende del sistema que utilice la planta.'}
  ]:[
   {title:'Change impact map',who:'For junior developers joining a React/TypeScript project or returning to code they did not write.',steps:['Select a change or feature','Explore files and dependencies','Understand relevance to the change','Prepare an evidence-based review'],deliverable:'A navigable map connecting the change to files, responsibilities and related tests.',stack:'TypeScript · AST · Git · Graph visualization',boundary:'Initial scope: verifiable static relationships. Dynamic calls and external dependencies require explicit review.'},
   {title:'Cross-shift quality continuity',who:'For supervisors and quality teams receiving open incidents from another shift and deciding what to address.',steps:['Link incident, batch and line','Define owner and next action','Review evidence and authorize closure','Hand over open actions'],deliverable:'A shift handover view with owners, dates, evidence and source-record references.',stack:'React · PostgreSQL · Role-based permissions',boundary:'Focus: follow-up on existing records. Integration depends on the system used by the plant.'}
  ]
 };
}
